# Generated by Django 5.2.1 on 2025-05-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('author', models.CharField()),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('unit', models.CharField(choices=[('unit2', 'Unit 2'), ('unit3', 'Unit 3'), ('unit7', 'Unit 7')], max_length=5)),
            ],
        ),
    ]
