# Generated by Django 5.2.1 on 2025-05-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_author_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_bacon',
            field=models.IntegerField(default=False),
        ),
    ]
