# Generated by Django 5.2.1 on 2025-05-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_document_is_bacon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_bacon',
            field=models.BooleanField(default=False),
        ),
    ]
